### PR TITLE
Use default block size with zstd compression

### LINKED ISSUE #64: Regression? higher startup time with zstd compression
I've been testing this appimagetool now that the static runtime is used automatically. I like that I can select the zstd compression level to use, however during testing I've noticed that appimages made with this appimagetool take longer to launch than appimages made with gzip compression.

For these benchmarks I've used the [zen-browser appimage ](https://github.com/zen-browser/desktop/releases/tag/1.0.0-a.13) (the specific build, which targets x86_64 v3). 

Using appimagetool I made two appimages, one using zstd level 22 compression (the highest):

`./appimagetool-x86_64.AppImage --comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 22 squashfs-root` which results in an appimage size of 73.7 MiB

And another using level 1:

`./appimagetool-x86_64.AppImage --comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 1 squashfs-root` which results in an appimage size of 96.0 MiB

And test it how long it took for each appimage to start, using this hacky script which gets when the application launches by checking the window class in i3wm: https://pastebin.com/qH7DwcQv

The appimages were all on placed on RAM before being launched to prevent the ssd causing any issue, here are the results: 

Screenshot: https://imgur.com/xzMirgX.png

First this is how long it takes for the original appimage to start after 4 passes: 

```
Time taken: 2359 miliseconds
Time taken: 2626 miliseconds
Time taken: 2257 miliseconds
Time taken: 2755 miliseconds
```

This is how long it takes for the zstd-22 appimage to start, which it is expected to be higher since it is using a very high compression level: 

````
Time taken: 3534 miliseconds
Time taken: 3571 miliseconds
Time taken: 3688 miliseconds
Time taken: 3767 miliseconds
````

This is how long it takes with zstd-1, odd that it still takes longer than the original appimage: 

```
Time taken: 2975 miliseconds
Time taken: 3116 miliseconds
Time taken: 2962 miliseconds
Time taken: 3130 miliseconds
```

Why I think that there is a regression, is that if we make the zstd squashfs image directly, and then add it to the runtime (bypass appimagetool all together) then, it only takes ~1.6 seconds to start the appimage as expected. 

```
Time taken: 1603 miliseconds
Time taken: 1619 miliseconds
Time taken: 1596 miliseconds
Time taken: 1632 miliseconds
```

That "manual" appimage was made using `mksquashfs ./squashfs-root Manual-zstd-1 -comp zstd -Xcompression-level 1` and then using the runtime [from here](https://github.com/AppImage/type2-runtime/releases/tag/continuous) I appended it with `cat Manual-zstd-1 >> runtime-x86_64`

I don't think this is an issue with the runtime, I don't know if the issue is that appimagetool is using different block sizes when making the squashfs image, there is a 1.4 MiB size difference between the manual-zstd1 appimage and the zstd1 appimage made with appimagetool.

### PR DESCRIPTION
**Pull request by Samueru-sama**
Indeed this was the problem, I just tested making an appimage with this appimagetool and I no longer have the issue of higher startup time. 

image

Fixes #64 

Build if someone wants to replicate my benchmarks: https://github.com/Samueru-sama/appimagetool/releases

### CODE REVIEW

**Comment by probonopd** [comment]
How do file sizes compare?

**Comment by Samueru-sama** [comment]
> How do file sizes compare?

In the zen-browser appimage, using the defaults which if I'm not mistaken it uses zstd level 15 and the only difference is the block size:

The 128K block size appimage is 0.3 MiB **smaller** than the 1MB block size appimage.

And when setting the compression level to level 1 the difference is 1.4 MiB in favor of the 128K block size appimage.

Worth mentioning that the startup time with the default compression level and 128K block size is about 1.8 Seconds, which is faster than the original gzip even.

**Comment by probonopd** [comment]
What we would also need to consider: How do the block sizes influence zsync efficiency? (zsync being used for delta updates with AppImageUpdate)

**Comment by Samueru-sama** [comment]
> What we would also need to consider: How do the block sizes influence zsync efficiency? (zsync being used for delta updates with AppImageUpdate)

I don't think there is going to be any significant difference, if at all it will likely be in favor of lower block size since it improves the read time considerably.

And in any case, I think it is far more important for appimages to start faster than a delay when updating, which is a far less common operation than launching the application, the current block size makes appimages take longer to start than they were when using gzip.

**Comment by probonopd** [comment]
It is a question of how large the updates are, how much traffic we produce. Think of people without high speed internet connection.

**Comment by Samueru-sama** [comment]
> It is a question of how large the updates are, how much traffic we produce. Think of people without high speed internet connection.

Oh sorry, In that case it is likely to be even less of a problem, the resulting appimage itself tends to be slightly smaller as well. 128K block size was the default being used for zstd before, it is also the default used by mksquashfs as far as I know it never had issues with zsync updates.

Is there some data that would suggest having higher block sizes improves zsync efficiency? I think we should always stick to defaults unless proven otherwise.

And btw I live in Venezuela, I lived most of my life having less than 4 mbit dsl internet, I know that pain very well hehe.

**Comment by probonopd** [comment]
> 
Is there some data that would suggest having higher block sizes improves zsync efficiency? I think we should always stick to defaults unless proven otherwise.

I don't know, but maybe you could do some experiements? This would be very valuable.

The use case is: Think if a big software package, like FreeCAD (many hundreds of MB). Imagine they do nightly builds. Updating to the latest nightly should be only a few MB, because not so much has changed overnight. That is the objective.

**Comment by Samueru-sama** [comment]
>I don't know, but maybe you could do some experiements? This would be very valuable.

I can do benchmarks, but I really don't know how to make the appimages with zsync to do the test on, it seems I would need to host two separate appimages and then measure the bandwidth usage on them.

I think this level of testing is something that should have been done when the block size was changed from 128K to 1M.

**Comment by probonopd** [comment]
For a somewhat realistic test, one could take, e.g., https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds, then extract it. First make an AppImage with zsync file of the unchanged AppDir, then change a few files in there (e.g., copy in a few libraries from your host system, overwriting the original ones) and create a new AppImage with zsync file. Then run AppImageUpdate on these.

A local web server (e.g., `sudo python3 -m http.server`) should do.

These types of tests are important but unfortunately no one never takes the time to do them.

**Comment by Samueru-sama** [comment]
> For a somewhat realistic test, one could take, e.g., https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds, then extract it. First make an AppImage with zsync file of the unchanged AppDir, then change a few files in there (e.g., copy in a few libraries from your host system, overwriting the original ones in the AppDir) and create a new AppImage with zsync file. Then run AppImageUpdate on these.
> 
> A local web server (e.g., `sudo python3 -m http.server`) should do.
> 
> These types of tests are important but unfortunately no one never takes the time to do them.

That's beyond my capabilities unfortunately.

The only way I see it is if I find a project that has a big appimage that already uses this very appimagetool with zsync updates already setup, and I would simply fork the project and modify it to use the appimagetool from my fork and compare the bandwidth usage when updating. But that will be very hard to find as most appimages don't even use the static runtime and zstd compression yet.

Is that testing needed for this to be merged?

**Comment by probonopd** [comment]
Let's say it would help to get this merged anytime soon.

**Comment by Samueru-sama** [comment]
> Let's say it would help to get this merged anytime soon.

I will interpret that as telling me that I need to carry that unrelated testing.

I think the burden is being shifted here, all that testing of zsync efficiency is something that should have been done when the block size was changed from the default size to 1MB.

Now that I found an actual bug with this change, and it is a significant regression, and the fix is a simple as using the default settings, you are asking me to carry testing on zsync efficiency?

I really don't know how to feel about this probono, hopefully I don't end up having to look for a different implementation of appimagetool that doesn't introduce this regression.

And it is not like I have a choice to go back to using gzip, because it is being dropped as an option as well.

**Comment by TheAssassin** [comment]
@Samueru-sama we are a really small team with a really limited amount of time. We could not afford sophisticated QA so far, we mostly rely on automated tests and extend them whenever appropriate. Combining multiple tools to perform a test adds some serious complexity even. This is an unfortunate exception to our normal conservative approach of keeping settings as-is. I think reverting to the default block size is a good idea therefore.

I hope I can spend more time again on AppImage, mostly focusing on reviews and security improvements. This should help us prevent such situations.

For the time being, we rely on our community to bring such issues to our attention. They use the tooling every single day and usually notice problems early on. So, thanks to you and all the others for debugging this.

@probonopd please avoid unexpected block size changes to random values in the future. I'm saying random because the values need to be multiples of zsync2's internal fixed blocksize for updates to work efficiently, for instance.

**Comment by probonopd** [comment]
@TheAssassin I won't make "unexpected" block size changes. I vaguely remembered that there was _some_ relationship between block size and zsync, but the details escaped me. Glad that you have deeper knowledge in this area.

**Comment by TheAssassin** [comment]
@probonopd AFAIR zsync2's zsyncmake2 variant supports arbitrary block sizes. This means that one could in theory use any block size. But we'll have to experiment with this.

File: src/appimagetool.c [hunk 1]
```diff
@@ -156,12 +156,13 @@ int sfs_mksquashfs(char *source, char *destination, int offset) {
...
-             * > Using a bigger block size than mksquashfs's default improves read speed and can produce smaller AppImages as well
-             * -- https://github.com/probonopd/go-appimage/commit/c4a112e32e8c2c02d1d388c8fa45a9222a529af3
+             * > Build with default 128K block size
+             * > It used to be 1M but that actually causes much higher startup times.
+             * > Some testing might be needed to see if there is some other value that actually improves performance.
+             * -- https://github.com/AppImage/appimagetool/issues/64
              */
             args[i++] = "-b";
-            args[i++] = "1M";
+            args[i++] = "128K";
```
Comment (TheAssassin) [inline src/appimagetool.c:165]: Do we need to define this _at all_? Default to me would mean "don't specify it".

Comment (probonopd) [reply src/appimagetool.c:165]: Explicit is better than implicit, isn't it?

Comment (TheAssassin) [reply src/appimagetool.c:165]: Well the goal is to use the default value. Why not leave that choice to the tool?

The value should work for zsync2, though.

**Review by TheAssassin — APPROVED** [review]
